const raValues = { 1: 38.5, 2: 36.2, 3: 33.0, 4: 29.1, 5: 25.8, 6: 24.0, 7: 25.2, 8: 28.7, 9: 32.9, 10: 36.6, 11: 38.3, 12: 38.7 };

const cropData = {
    // Grãos e Cereais
    'soja': { label: 'Soja', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.4 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.8 }, 'pico': { label: 'Pico (51-90d)', kc: 1.15 }, 'final': { label: 'Maturação (91-115d)', kc: 0.5 } } },
    'milho': { label: 'Milho', stages: { 'inicial': { label: 'Inicial (0-30d)', kc: 0.4 }, 'desenvolvimento': { label: 'Desenvolvimento (31-70d)', kc: 0.8 }, 'pico': { label: 'Pico (71-110d)', kc: 1.2 }, 'final': { label: 'Maturação (111-140d)', kc: 0.7 } } },
    'feijao': { label: 'Feijão', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.45 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.75 }, 'pico': { label: 'Pico (51-80d)', kc: 1.1 }, 'final': { label: 'Maturação (81-100d)', kc: 0.4 } } },
    'arroz': { label: 'Arroz', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 1.05 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 1.1 }, 'pico': { label: 'Pico (51-90d)', kc: 1.2 }, 'final': { label: 'Final (91-120d)', kc: 0.9 } } },
    'trigo': { label: 'Trigo', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.3 }, 'desenvolvimento': { label: 'Desenvolvimento (21-60d)', kc: 0.8 }, 'pico': { label: 'Pico (61-95d)', kc: 1.15 }, 'final': { label: 'Final (96-120d)', kc: 0.3 } } },
    'sorgo': { label: 'Sorgo', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.4 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.75 }, 'pico': { label: 'Pico (51-80d)', kc: 1.1 }, 'final': { label: 'Final (81-100d)', kc: 0.55 } } },
    'aveia': { label: 'Aveia', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.3 }, 'desenvolvimento': { label: 'Desenvolvimento (21-60d)', kc: 0.75 }, 'pico': { label: 'Pico (61-95d)', kc: 1.15 }, 'final': { label: 'Final (96-120d)', kc: 0.25 } } },
    'cevada': { label: 'Cevada', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.3 }, 'desenvolvimento': { label: 'Desenvolvimento (21-60d)', kc: 0.75 }, 'pico': { label: 'Pico (61-95d)', kc: 1.15 }, 'final': { label: 'Final (96-120d)', kc: 0.25 } } },
    'centeio': { label: 'Centeio', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.3 }, 'desenvolvimento': { label: 'Desenvolvimento (21-60d)', kc: 0.75 }, 'pico': { label: 'Pico (61-95d)', kc: 1.15 }, 'final': { label: 'Final (96-120d)', kc: 0.25 } } },

    // Hortaliças
    'batata': { label: 'Batata', stages: { 'inicial': { label: 'Inicial (0-25d)', kc: 0.5 }, 'desenvolvimento': { label: 'Desenvolvimento (26-60d)', kc: 0.8 }, 'pico': { label: 'Pico (61-100d)', kc: 1.15 }, 'final': { label: 'Maturação (101-130d)', kc: 0.75 } } },
    'tomate': { label: 'Tomate', stages: { 'inicial': { label: 'Inicial (0-25d)', kc: 0.6 }, 'desenvolvimento': { label: 'Desenvolvimento (26-50d)', kc: 0.85 }, 'pico': { label: 'Pico (51-90d)', kc: 1.15 }, 'final': { label: 'Maturação (91-120d)', kc: 0.8 } } },
    'cebola': { label: 'Cebola', stages: { 'inicial': { label: 'Inicial (0-15d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (16-70d)', kc: 1.0 }, 'final': { label: 'Maturação (71-90d)', kc: 0.75 } } },
    'alface': { label: 'Alface', stages: { 'inicial': { label: 'Inicial (0-15d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (16-40d)', kc: 0.9 }, 'pico': { label: 'Pico (41-60d)', kc: 1.0 } } },
    'cenoura': { label: 'Cenoura', stages: { 'inicial': { label: 'Inicial (0-25d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (26-70d)', kc: 1.05 }, 'final': { label: 'Final (71-90d)', kc: 0.95 } } },
    'alho': { label: 'Alho', stages: { 'inicial': { label: 'Inicial (0-15d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (16-70d)', kc: 1.0 }, 'final': { label: 'Final (71-100d)', kc: 0.7 } } },
    'abobora': { label: 'Abóbora', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.5 }, 'desenvolvimento': { label: 'Desenvolvimento (21-60d)', kc: 0.8 }, 'pico': { label: 'Pico (61-90d)', kc: 1.0 }, 'final': { label: 'Final (91-110d)', kc: 0.75 } } },
    'pepino': { label: 'Pepino', stages: { 'inicial': { label: 'Inicial (0-15d)', kc: 0.6 }, 'desenvolvimento': { label: 'Desenvolvimento (16-40d)', kc: 0.9 }, 'pico': { label: 'Pico (41-60d)', kc: 1.1 }, 'final': { label: 'Final (61-75d)', kc: 0.8 } } },
    'pimentao': { label: 'Pimentão', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.6 }, 'desenvolvimento': { label: 'Desenvolvimento (21-55d)', kc: 0.85 }, 'pico': { label: 'Pico (56-90d)', kc: 1.1 }, 'final': { label: 'Final (91-110d)', kc: 0.9 } } },
    'berinjela': { label: 'Berinjela', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.6 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.85 }, 'pico': { label: 'Pico (51-80d)', kc: 1.1 }, 'final': { label: 'Final (81-100d)', kc: 0.9 } } },
    'repolho': { label: 'Repolho', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.9 }, 'pico': { label: 'Pico (51-70d)', kc: 1.0 }, 'final': { label: 'Final (71-85d)', kc: 0.95 } } },
    'couveflor': { label: 'Couve-flor', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.9 }, 'pico': { label: 'Pico (51-75d)', kc: 1.0 }, 'final': { label: 'Final (76-90d)', kc: 0.95 } } },
    'espinafre': { label: 'Espinafre', stages: { 'inicial': { label: 'Inicial (0-15d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (16-35d)', kc: 0.9 }, 'pico': { label: 'Pico (36-50d)', kc: 1.0 }, 'final': { label: 'Final (51-60d)', kc: 0.95 } } },
    'brocolis': { label: 'Brócolis', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.9 }, 'pico': { label: 'Pico (51-75d)', kc: 1.0 }, 'final': { label: 'Final (76-90d)', kc: 0.95 } } },
    'couve': { label: 'Couve', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.7 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.9 }, 'pico': { label: 'Pico (51-75d)', kc: 1.0 }, 'final': { label: 'Final (76-90d)', kc: 0.95 } } },

    // Frutas
    'laranja': { label: 'Laranja', stages: { 'jovem': { label: 'Pomar Jovem (1-3a)', kc: 0.7 }, 'adulto': { label: 'Pomar Adulto (>3a)', kc: 0.95 } } },
    'manga': { label: 'Manga', stages: { 'jovem': { label: 'Pomar Jovem (1-4a)', kc: 0.7 }, 'adulto': { label: 'Pomar Adulto (>4a)', kc: 1.0 } } },
    'uva': { label: 'Uva', stages: { 'inicial': { label: 'Inicial (0-30d)', kc: 0.3 }, 'desenvolvimento': { label: 'Folhas (31-70d)', kc: 0.7 }, 'pico': { label: 'Frutificação (71-120d)', kc: 0.85 }, 'final': { label: 'Final (121-150d)', kc: 0.45 } } },
    'abacaxi': { label: 'Abacaxi', stages: { 'unico': { label: 'Ciclo Completo (18m)', kc: 0.5 } } },
    'melancia': { label: 'Melancia', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.4 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.75 }, 'pico': { label: 'Pico (51-80d)', kc: 1.0 }, 'final': { label: 'Final (81-95d)', kc: 0.75 } } },
    'maracuja': { label: 'Maracujá', stages: { 'unico': { label: 'Ciclo Completo (1-2a)', kc: 1.05 } } },
    'morango': { label: 'Morango', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.3 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.7 }, 'pico': { label: 'Pico (51-80d)', kc: 0.95 }, 'final': { label: 'Colheita (81-100d)', kc: 0.65 } } },
    'banana': { label: 'Banana', stages: { 'unico': { label: 'Ciclo Completo (9-12m)', kc: 1.1 } } },
    'mamao': { label: 'Mamão', stages: { 'unico': { label: 'Ciclo Completo (1a)', kc: 1.0 } } },
    'abacate': { label: 'Abacate', stages: { 'jovem': { label: 'Pomar Jovem (1-3a)', kc: 0.75 }, 'adulto': { label: 'Pomar Adulto (>3a)', kc: 0.95 } } },
    'caju': { label: 'Caju', stages: { 'unico': { label: 'Ciclo Completo (>3a)', kc: 0.95 } } },
    'goiaba': { label: 'Goiaba', stages: { 'unico': { label: 'Ciclo Completo (>2a)', kc: 0.95 } } },
    'limao': { label: 'Limão', stages: { 'jovem': { label: 'Pomar Jovem (1-3a)', kc: 0.7 }, 'adulto': { label: 'Pomar Adulto (>3a)', kc: 0.95 } } },
    'melao': { label: 'Melão', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.4 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.75 }, 'pico': { label: 'Pico (51-70d)', kc: 1.0 }, 'final': { label: 'Final (71-80d)', kc: 0.75 } } },
    'kiwi': { label: 'Kiwi', stages: { 'inicial': { label: 'Inicial (0-30d)', kc: 0.3 }, 'desenvolvimento': { label: 'Desenvolvimento (31-90d)', kc: 0.7 }, 'pico': { label: 'Pico (91-150d)', kc: 0.95 }, 'final': { label: 'Final (151-180d)', kc: 0.65 } } },
    'pessego': { label: 'Pêssego', stages: { 'jovem': { label: 'Pomar Jovem (1-2a)', kc: 0.7 }, 'adulto': { label: 'Pomar Adulto (>2a)', kc: 0.95 } } },
    'ameixa': { label: 'Ameixa', stages: { 'jovem': { label: 'Pomar Jovem (1-2a)', kc: 0.7 }, 'adulto': { label: 'Pomar Adulto (>2a)', kc: 0.95 } } },
    'figo': { label: 'Figo', stages: { 'jovem': { label: 'Pomar Jovem (1-2a)', kc: 0.7 }, 'adulto': { label: 'Pomar Adulto (>2a)', kc: 0.95 } } },

    // Industriais e Outros
    'cana': { label: 'Cana-de-açúcar', stages: { 'inicial': { label: 'Inicial (0-30d)', kc: 0.4 }, 'desenvolvimento': { label: 'Desenvolvimento (31-90d)', kc: 0.85 }, 'pico': { label: 'Pico (91-270d)', kc: 1.25 }, 'final': { label: 'Maturação (271-365d)', kc: 0.75 } } },
    'cafe': { label: 'Café', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.85 }, 'producao': { label: 'Produção (>2a)', kc: 1.1 } } },
    'algodao': { label: 'Algodão', stages: { 'inicial': { label: 'Inicial (0-25d)', kc: 0.35 }, 'desenvolvimento': { label: 'Desenvolvimento (26-60d)', kc: 0.75 }, 'pico': { label: 'Pico (61-100d)', kc: 1.2 }, 'final': { label: 'Final (101-135d)', kc: 0.6 } } },
    'girassol': { label: 'Girassol', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.35 }, 'desenvolvimento': { label: 'Desenvolvimento (21-55d)', kc: 0.75 }, 'pico': { label: 'Pico (56-90d)', kc: 1.1 }, 'final': { label: 'Final (91-110d)', kc: 0.4 } } },
    'mandioca': { label: 'Mandioca', stages: { 'unico': { label: 'Ciclo Completo (12-18m)', kc: 0.85 } } },
    'fumo': { label: 'Fumo', stages: { 'inicial': { label: 'Inicial (0-25d)', kc: 0.4 }, 'desenvolvimento': { label: 'Desenvolvimento (26-60d)', kc: 0.75 }, 'pico': { label: 'Pico (61-90d)', kc: 1.1 }, 'final': { label: 'Final (91-110d)', kc: 0.8 } } },
    'eucalipto': { label: 'Eucalipto', stages: { 'unico': { label: 'Ciclo Completo (>2a)', kc: 0.95 } } },
    'seringueira': { label: 'Seringueira', stages: { 'unico': { label: 'Ciclo Completo (>6a)', kc: 1.0 } } },
    'sisal': { label: 'Sisal', stages: { 'unico': { label: 'Ciclo Completo (>2a)', kc: 0.8 } } },
    'dende': { label: 'Dendê', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 1.0 } } },
    'pimenta': { label: 'Pimenta', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.6 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.85 }, 'pico': { label: 'Pico (51-90d)', kc: 1.1 }, 'final': { label: 'Final (91-120d)', kc: 0.9 } } },
    'cacau': { label: 'Cacau', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 1.0 } } },
    'guarana': { label: 'Guaraná', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 1.0 } } },
    'castanha_do_para': { label: 'Castanha-do-Pará', stages: { 'unico': { label: 'Ciclo Completo (>10a)', kc: 1.0 } } },
    'carnauba': { label: 'Carnaúba', stages: { 'unico': { label: 'Ciclo Completo (>5a)', kc: 0.9 } } },
    'babacu': { label: 'Babaçu', stages: { 'unico': { label: 'Ciclo Completo (>5a)', kc: 0.9 } } },
    'pupunha': { label: 'Pupunha', stages: { 'unico': { label: 'Ciclo Completo (>2a)', kc: 0.95 } } },
    'acai': { label: 'Açaí', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 1.0 } } },
    'cupuacu': { label: 'Cupuaçu', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 1.0 } } },
    'graviola': { label: 'Graviola', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'jenipapo': { label: 'Jenipapo', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 0.95 } } },
    'umbu': { label: 'Umbu', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 0.95 } } },
    'cajueiro': { label: 'Cajueiro', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 0.95 } } },
    'mangaba': { label: 'Mangaba', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 0.95 } } },
    'siriguela': { label: 'Siriguela', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'acerola': { label: 'Acerola', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'jabuticaba': { label: 'Jabuticaba', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 0.95 } } },
    'figueira': { label: 'Figueira', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'caqui': { label: 'Caqui', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'lichia': { label: 'Lichia', stages: { 'jovem': { label: 'Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Produção (>3a)', kc: 0.95 } } },
    'roma': { label: 'Romã', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'amora': { label: 'Amora', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'framboesa': { label: 'Framboesa', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'mirtilo': { label: 'Mirtilo', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'physalis': { label: 'Physalis', stages: { 'inicial': { label: 'Inicial (0-20d)', kc: 0.6 }, 'desenvolvimento': { label: 'Desenvolvimento (21-50d)', kc: 0.85 }, 'pico': { label: 'Pico (51-90d)', kc: 1.1 }, 'final': { label: 'Maturação (91-120d)', kc: 0.9 } } },
    'pitaia': { label: 'Pitaya', stages: { 'jovem': { label: 'Jovem (1-2a)', kc: 0.7 }, 'producao': { label: 'Produção (>2a)', kc: 0.95 } } },
    'tangerina': { label: 'Tangerina', stages: { 'jovem': { label: 'Pomar Jovem (1-3a)', kc: 0.7 }, 'producao': { label: 'Pomar Adulto (>3a)', kc: 0.95 } } },
    'pimenta_do_reino': { label: 'Pimenta-do-reino', stages: { 'inicial': { label: 'Inicial (0-30d)', kc: 0.6 }, 'desenvolvimento': { label: 'Desenvolvimento (31-180d)', kc: 0.75 }, 'producao': { label: 'Produção (>180d)', kc: 0.9 } } },
};